version: '3.8'
services:
  backend:
    build:
      context: backend/gold_price_service
      dockerfile: Dockerfile
    environment:
      RUST_LOG: "info"
    ports:
      - "8080:8080"
    restart: "always"
    working_dir: /usr/src/app
    volumes:
      - ./backend/gold_price_service/target:/usr/src/app/target
    command: ["/usr/local/bin/gold_price_service"]
    networks:
      - app-network

  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    environment:
      NODE_ENV: "production"
      HOSTNAME: "0.0.0.0"
      BACKEND_URL: "http://backend:8080"
    ports:
      - "3000:3000"
    restart: "always"
    working_dir: /app
    volumes:
      # - ./frontend/:/app
      - /app/node_modules
    command: ["node", "server.js"]
    networks:
      - app-network


networks:
  app-network:
    driver: bridge