version: '3'
services:
  gold-price-tracker-frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    environment:
      NODE_ENV: "production"
    ports:
      - "3000:3000"
    restart: "always"
    working_dir: /app
    volumes:
      # Use node_modules from the image
      # - ./frontend/:/app
      - /app/node_modules
    command: ["node", "server.js"]