version: '3'
services:
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    environment:
      NODE_ENV: "production"
    ports:
      - "3000:3000"
    restart: "always"
    working_dir: /app
    volumes:
      # Use node_modules from the image
      # - ./frontend/:/app
      - /app/node_modules
    command: ["node", "server.js"]
  backend:
    build:
      context: backend/gold_price_service
      dockerfile: Dockerfile
    environment:
      RUST_LOG: "info"
    ports:
      - "8080:8080"
    restart: "always"
    working_dir: /usr/src/app
    volumes:
      - /usr/src/app/target
    command: ["/usr/local/bin/gold_price_service"]