FROM rust:1.81
WORKDIR /usr/src/app
RUN curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash && \
    cargo binstall cargo-watch -y
COPY Cargo.toml Cargo.lock ./
RUN cargo fetch
COPY . .
EXPOSE 8080
CMD ["cargo", "watch", "-x", "run"]