# Generated by Django 5.0.7 on 2024-07-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rate_22kt', models.FloatField()),
                ('rate_24kt', models.FloatField()),
            ],
        ),
    ]
