# Generated by Django 5.0.7 on 2024-08-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_rate_admin', '0002_rate_arhiant_rate_24kt_rate_arihant_rate_22kt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='rate',
            name='arhiant_rate_24kt',
            field=models.IntegerField(default=7500),
        ),
        migrations.AlterField(
            model_name='rate',
            name='arihant_rate_22kt',
            field=models.IntegerField(default=6850),
        ),
        migrations.AlterField(
            model_name='rate',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate_22kt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate_24kt',
            field=models.IntegerField(),
        ),
    ]
