# Generated by Django 5.1 on 2024-08-29 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold_rate_admin', '0003_alter_rate_options_alter_rate_arhiant_rate_24kt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='arhiant_rate_24kt',
            new_name='arihant_rate_24kt',
        ),
    ]
