# Generated by Django 5.1 on 2025-04-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gold_rate_admin", "0004_rename_arhiant_rate_24kt_rate_arihant_rate_24kt"),
    ]

    operations = [
        migrations.AddField(
            model_name="rate",
            name="arihant_rate_18kt",
            field=models.IntegerField(default=7500),
        ),
    ]
