# Generated by Django 4.2.21 on 2025-05-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_rate_admin', '0005_rate_arihant_rate_18kt'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='rate_18kt',
            field=models.IntegerField(default=7500),
        ),
    ]
