# Generated by Django 4.2.23 on 2025-06-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_rate_admin', '0006_rate_rate_18kt'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='arihant_silver',
            field=models.IntegerField(default=106),
        ),
        migrations.AddField(
            model_name='rate',
            name='rate_silver',
            field=models.IntegerField(default=106),
        ),
    ]
