# Generated by Django 4.2.23 on 2025-06-26 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold_rate_admin', '0007_rate_arihant_silver_rate_rate_silver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='arihant_silver',
            new_name='arihant_rate_silver',
        ),
    ]
