# Generated by Django 4.2.23 on 2026-01-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_rate_admin', '0008_rename_arihant_silver_rate_arihant_rate_silver'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='is_manual_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rate',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
