# Generated by Django 4.2.23 on 2026-05-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gold_rate_admin", "0010_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate_999", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("status", models.CharField(default="pending", max_length=20)),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("quantity_grams", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MetalInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metal", models.CharField(max_length=20)),
                ("available_grams", models.IntegerField()),
                ("reserved_grams", models.IntegerField(default=0)),
            ],
        ),
    ]
