# Generated by Django 4.2.30 on 2026-08-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gold_rate_admin", "0011_bookinglock_metalinventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="rate",
            name="rate_24kt_9999",
            field=models.IntegerField(default=7500),
        ),
    ]
